### ISSUE TITLE
Use new otel-collector distribution based on otel-collector 0.104.0

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#1207]
**Description**

In order to use the new receivers in https://github.com/kyma-project/opentelemetry-collector-components the distro needs to get officially released and then used in the telemetry-manager.

**Tasks**
- [x]  Add missing dependabot config to the https://github.com/kyma-project/opentelemetry-collector-components repo
- [x] Add missing security scanner config to the https://github.com/kyma-project/opentelemetry-collector-components repo
- [x] Remove third-party-images [folder](https://github.com/kyma-project/third-party-images/tree/main/otel-collector) and related prow job 
  https://github.com/kyma-project/third-party-images/pull/439
  https://github.com/kyma-project/test-infra/pull/11223
- [x] Remove [dummymetricsreceiver](https://github.com/kyma-project/opentelemetry-collector-components/tree/main/receiver/dummymetricsreceiver) or make it pretty (add proper README.md and have tests)
- [x] Update to latest otel-collector (done by dependabot, loadtest triggered using: https://github.com/kyma-project/telemetry-manager/pull/1232)
- [x] Release new distribution ([0.104.0-1.20.0-rc1](https://github.com/kyma-project/opentelemetry-collector-components/releases/tag/1.20.0-rc1), http://europe-docker.pkg.dev/kyma-project/prod/kyma-otel-collector:0.104.0-1.20.0-rc1)
- [x] [Use the released image in telemetry-manager](https://github.com/kyma-project/telemetry-manager/pull/1232)

**Criteria**
- [X] The new otel-collector image sourced by the https://github.com/kyma-project/opentelemetry-collector-components repo is in use by the telemetry-manager
- [x] The old sources are gone

**Reasons**

**Attachments**

**Release Notes**

```

```
