### ISSUE TITLE
Transform & Filter support for OTel pipelines

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#1293]
**Description**
Users like the way it is by getting a kind of managed agent support to easily start collecting telemetry data. The usual integration with CloudLogging seem to fit even from the requirement perspective, however, as soon as a custom output gets used, custom filters for LogPipelines are getting used. Also, often I wanted to recommend to filter out some metrics coming with the default setup, where such possibility is missing at the moment.

Requirements:
- Have a way to enrich data with cluster specific data attributes
- Have a way to filter out data which is not relevant for the use case
- The support should be equivalent across all Otel based pipelines, using similar syntax and semantics

Idea:
- All generic filter and transformation logic in otel-collector-contrib seem to get consolidated into one main processors, [filterprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/filterprocessor/README.md) and [transformprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor), being both based on [OTTL](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl).
- Provide support for these two processors, and all major needs in regards to filter and transform will be covered

Typical Use cases:
- Add one cluster identifier resource attribute like for dynatrace
- Do typical transformations as needed for dynatrace, see [integration guide values.yaml](https://github.com/kyma-project/telemetry-manager/blob/main/docs/user/integration/dynatrace/exporter-values.yaml)
- Add proper span.status in case of 4xx responses
- filter out metrics by name pattern like "k8s.node.*"

Tasks:
- [x] Preparation
  - [x] #1483
  - [x] Come up with an API proposal
          - Do you need to have multiple filter and transform rules with a flexible order, or is one block for each in a fixed order is enough? 
          - Can it be on root level or do we need an additional umbrella attribute "processors"?
  - [x] List transform rules used by customers in production as test cases
  - [x] Align API with cumulativeToDelta support (https://github.com/kyma-project/telemetry-manager/pull/2301)
  - [x] Identify all OTTL functions which we want to support (https://github.com/kyma-project/telemetry-manager/pull/2322)
 - [x] Implementation of transform API
   - [x] Introduce Transform API in all pipelines for experimental only (https://github.com/kyma-project/telemetry-manager/issues/2349)
   - [x] Write a generic e2e tests for all components (https://github.com/kyma-project/telemetry-manager/issues/2379)
   - [x] Add verification logic with e2e tests https://github.com/kyma-project/telemetry-manager/issues/2417
 - [x] Implementation of filter API (https://github.com/kyma-project/telemetry-manager/issues/2551)
   - [x] Introduce API for experimental 
   - [x] Write a generic e2e tests for all components
   - [x] Add verification logic
 - [ ] Validating webhook for all 3 pipeline types (https://github.com/kyma-project/telemetry-manager/issues/2633)
 - [x] Documentation (https://github.com/kyma-project/telemetry-manager/issues/2634)
 - [x] Document compatibility procedure for OTTL functions and general otel-collector upgrade procedure (https://github.com/kyma-project/telemetry-manager/issues/2635)
 - [x] Kyma Dashboard config (view and edit) (https://github.com/kyma-project/telemetry-manager/issues/2635)
 - [x] Remove feature flag (https://github.com/kyma-project/telemetry-manager/issues/2635)
 
**FluentBit use cases**
```yaml
- custom: |
   Name  grep
   Exclude path /healthz/ready
```

```yaml
- custom: |
    Name type_converter
    uint_key response_code response_code_str string
- custom: |
    Name grep
    Exclude  $response_code_str ^2\d\d$
```

```yaml
- custom: |
   Name  record_modifier
   Record cluster_id public-cluster
```

```yaml
- custom: |
   Name modify
   Condition Key_Value_Equals logger HttpAccessLog
   Condition Key_value_does_not_match k8s_namespace ^(compass-system|istio-system|kyma-system|kube-system)$
   Add logType httpAccess
```

```yaml
filters:
 - custom: |
   Name  lua
 files:
 - content: |
   function transform_log_level_uppercase(tag, timestamp, record)
     if type(record) ~= "table" then
       return 1, timestamp, record
     end
     if record["level"] and type(record["level"]) == "string" then
       local level = record["level"]:lower()
       if level == "info" or level == "error" or level == "warn" or level == "warning" or level == "debug" then
         record["level"] = level:upper()
       end
     end
     return 1, timestamp, record
   end
   function transform_log_keys(tag, timestamp, record)
     if type(record) ~= "table" then
       return 1, timestamp, record
     end
     local keys_to_convert = {
       ["WorkflowId"] = "workflow_id",
       ["RunId"] = "run_id",
       ["WorkflowType"] = "workflow_type"
     }
     for old_key, new_key in pairs(keys_to_convert) do
       if record[old_key] then
         record[new_key] = record[old_key]
         record[old_key] = nil
       end
     end
     return 1, timestamp, record
   end
   function process_log(tag, timestamp, record)
     local _, new_timestamp, new_record = transform_log_level_uppercase(tag, timestamp, record)
     return transform_log_keys(tag, new_timestamp, new_record)
   end
```

**Comment by a-thaler** [comment]
The progress of the story is represented by the checkbox list in the ticket description.

The filter feature was delayed as we found challenges with the current state of the underlying filterprocessor. We solved all issues and currently are finalizing the feature. Afterwards, mainly side-tasks are still to solve like writing documentation.

**Comment by a-thaler** [comment]
Included in release 1.52.0 without validating webhook for now (only server side validation is happening so that configuration errors are visible in the status of the pipelines)
