### ISSUE TITLE
Remove validation webhook for LogPipelines

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#1392]
**Description**
Out of the experiences gathered, an advanced validation of a pipeline should not be done in a webhook as it takes time, might not be available and anyway need to get repeated at server side again.
Syntactical checks can be done nicely in the CRD definition already.

So the gola is to move all parts of the current webhook to an adequate replacement and get rid of the webhook

**Criterias**
- The webhook is removed
- All validation got replaced by adequate replacements

**Tasks**
     - [ ] Move unsupported mode warning
     - [ ] Max Pipeline check to be executed on backend side similar to TracePipeline, having proper status change
     - [ ] Singleton check for telemetry resource https://github.com/kyma-project/telemetry-manager/issues/555
     - [ ] Plugin validation with supported list and hardcoded available plugin list as backend validation feature reflected via status change
     - [ ] Missing file/variable reference validation
     - [x] Delete dry-run and get manager image free (https://github.com/kyma-project/telemetry-manager/issues/1234)
     - [ ] Move API validation into CRD schema validation
     - [ ] Delete webhook

**Reasons**

**Attachments**

**Release Notes**

```

```

**Comment by a-thaler** [comment]
We decided to stay with the validating webhook. The heavy operation of performing dry-runs was removed. We anyway will not get rid of webhooks and the cert mechanism seem to work reliable. So instead we will focus on shifting to OTEL and remove the webhook once we remove fluentbit
