### ISSUE TITLE
[Telemetry] Annotation based scraping support

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#513]
**Description**
As part of https://github.com/kyma-project/kyma/issues/13079 the MVP should not only contain the initial metrics gateway setup but should already support scraping custom metrics from applications. This story should implement a basic setup.

The initial API should similar to this:

```YAML
kind: MetricPipeline
apiVersion: telemetry.kyma-project.io/v1alpha1
metadata:
  name: myPipeline
spec:
  input: # Metrics will be received via OTLP to the gateway always. Additionally you can enable different inputs to send additional metrics to the gateway. Metrics are selected based on labels
    application: # activates app-scraper by annotation
      namespaces: # maps to filterprocessor
        include: []
        exclude: []
        system: true # enables system namespaces for scraping as well
      prometheus:
        enabled: true
      runtime: # (container runtime) activates cadvisor scraping (kubeletreceiver)
        enabled: true
      istio: # activates istio scraping. Filter by `destination_service_namespace` or `destination_workload_namespace` if namespaces are limited
        enabled: true
```

Having one pipeline which enables the application input, will trigger the deployment of a new agent running as daemonset. That new agent will run the following receivers:
- prometheusreceiver/app: annotation based scraping of the custom application endpoints running on that node
- prometheusreceiver/istio: annotation based scraping of the istio endpoint running on the node
- kubeletreceiver: determine kubelet metrics for the node

As the resource.service.name attribute cannot be easily determined in the context of the scraping itself (as no further info from APIServer is available at that stage), the service.name should be treated as undefined, so that a general enrichment login in the gateway can kick-in by determining a default service name.
The defaulting logic of the service.name should be similar to istio. If a pod can be determined as source (using the k8sattributeprocessor), then check for the typical app labels and leverage them. If not available, then use the canonical name for the pod (deployment/statefuleset/.. name)

As multiple pipelines could use a different scrape config regarding namespaces, the junction of all configured namespaces should be scraped and then filtered in the gateway. To indicate that a metric is sourced by a specific agent, an additional resource attribute like `kyma.source=prometheusreceiver/app` should be enriched per receiver/agent, then the namespace filtering can happen on the basis of that attribute and potentially removed again.

**Mandatory Tasks**
- [x] Prepare config generation: [View PR](https://github.com/kyma-project/telemetry-manager/pull/249)
- [x] Pod annotation scraping: [View Issue](https://github.com/kyma-project/kyma/issues/17828)
- [x] Kubelet Stats receiver: [View Issue](https://github.com/kyma-project/kyma/issues/17830)
- [x] Service annotation scraping: [View Issue](https://github.com/kyma-project/telemetry-manager/issues/318)
- [x] Istio envoy and HTTPS scraping (test is mandatory) (https://github.com/kyma-project/telemetry-manager/issues/349)
- [x] Hardened setup (https://github.com/kyma-project/telemetry-manager/issues/375)
- [ ] Self-monitoring via annotation (https://github.com/kyma-project/telemetry-manager/issues/348)
- [ ] Reflect metric agent status In metric pipeline status (https://github.com/kyma-project/kyma/issues/18066)
- [ ] Namespace selector (test is mandatory)
- [ ] https://github.com/kyma-project/telemetry-manager/issues/336
- [x] Filter out traces for scraping
- [x] Consolidate the scrape relabel configs with the upstream chart (https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml)

**Comment by a-thaler** [comment]
Basic feature is implemented
