### ISSUE TITLE
Use consistent labelling

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#646]
**Description**

Use a consistent module label and common label selectors for the telemetry-manager and its resources.

**Criterias**
- All resources of the module can be found by a simple label selector defining the module name
- All resources of the module are following labelling best practices
- Align with https://github.com/kyma-project/community/issues/864.
- There should be one central place where the labels/selectors are defined.
- Check if we should use the [commonLabels](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/transformerconfigs/README.md#labels-transformer) construct in the kustomization [config](https://github.com/kyma-project/eventing-manager/blob/main/config/default/kustomization.yaml).
- If selectors cannot be easily changed, we will keep them

**Implementation**
The story should be split into the resources part of the module resources managed by lifecycle-manager/user and the resources managed by the telemetry-manager. Changing the labels will be a problem for podSelectors which are immutable fields, so all workload needs to be re-created.

- Module resources
  - [x] Rename the telemetry-manager and adjust labels as part of https://github.com/kyma-project/telemetry-manager/issues/651
  - [x] Rename all labels in the module resources (https://github.com/kyma-project/telemetry-manager/issues/874)
  - [x] Add "module" label (https://github.com/kyma-project/telemetry-manager/issues/1783)
- Manager resources
  - [x] Rename the telemetry collector and change the podSelector labels as part of https://github.com/kyma-project/telemetry-manager/issues/652
  - [x] Rename podSelectors for metric gateway and metric agent
  - [x] Enrich all labels of trace/metrics domain
  - [x] Enrich all labels of log domain

**Comment by a-thaler** [comment]
The istio module applied labelling already, see https://kyma-project.io/#/istio/user/00-10-overview-istio-controller?id=labeling-resources

**Comment by a-thaler** [comment]
Adjusted all regular labels and tried to make it consistent were possible. Have not touched selector labels as this will require bigger investments which is not worth the effort.
