### ISSUE TITLE
[Telemetry Manager] E2E metric test based on new setup having no dependency to a backend

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#72]
Instead of refactoring the old "fast-integration" tests in the kyma repo we want to build up a new test suite based on ginko/golang in the telemetry-manager repo. A first step was done already by bringing basic tests for the manager itself and an e2e setup for traces. Now it is time to extend it to test the ne metrics functionality. Hereby, the focus is on having a backend for metric consumption in place not dependent on a 3party backend, but more optimized for testing and verification.

## Acceptance Criteria
- Have at least one new test case assuring that metric collection is working as expected
  - Verify that a MetricPipeline results in a new otel-collector deployment which comes up proper, incl metrics endpoint
  - Verify that a sample metric gets processed successful
- Have a Ginkgo helper to search by metric name and potentially a metric attribute
- Have a mock backend used with some nice documentation on how to use it
- The code lies in the new telemetry manager repository

## Reference
- https://github.com/kyma-project/telemetry-manager/pull/44
- https://github.com/kyma-project/telemetry-manager/issues/57

## Action steps
- [x] Split the E2E and the telemetry-operator source code (the E2E test suite introduces its own set of dependencies that bloat the resulting image, what leads to security scanner warnings).
- [x] Extract the infrastructure orchestration into the separate **`toolkit`** package: cluster orchestration, OTEL-client, Gomega helpers. The **`toolkit`** module should make it possible to write an arbitrary E2E test in less than 10 minutes.
- [x] Implement basic metric test using the **`toolkit`** module testing both exporter protocols.
- [x] ~~Cluster the E2E tests by features to reach granularity in test results (the failed tests should have the minimal possible scope)~~. Skipping due to the paucity of test scenarios.
