### ISSUE TITLE
Telemetry Beta API

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#767]
**Description**
The telemetry API should head towards a proper v1 version and requires the step to a beta version as next step. For the logs and trace API, smaller things should get adjusted like changing the status to be conform to k8s conventions (https://github.com/kyma-project/telemetry-manager/issues/601). For logs the Loki output needs to get removed and the API prepared for OTLP support (https://github.com/kyma-project/telemetry-manager/issues/556).

The goal is to get a streamlined API across all pipeline types with a betaV1 version, having:
- consistent status handling
- consistent OTLP output handling
- consistent input handling

Action:
- [x] Preparations
  - [X] Understand the k8s API restrictions and outline a path to a beta version (https://github.com/kyma-project/telemetry-manager/issues/712)
- [x] Implementation
  - [x] Align existing status API of logs and traces with syntactical kubernetes conventions (https://github.com/kyma-project/telemetry-manager/issues/772)
  - [x] Introduce new status API for logs and traces, mark the old one as deprecated (https://github.com/kyma-project/telemetry-manager/issues/805)
  - [x] Prepare experimental beta feature: Introduce feature flag and adjust kustomize deployment to deploy dummy beta version only when active (https://github.com/kyma-project/telemetry-manager/issues/848)
  - [x] Remove old stats from traces and logs in beta version
  - [x] Remove loki output from alpha and beta version (https://github.com/kyma-project/telemetry-manager/issues/873)
  - [x] Introduce conversion webhook for beta version (https://github.com/kyma-project/telemetry-manager/issues/1391)
  - [x] Switch to default handling via webhook to support namespaceSelector feature (https://github.com/kyma-project/telemetry-manager/issues/1541)
  - [x] Adjust namespace selector for LogPipeline (https://github.com/kyma-project/telemetry-manager/issues/1395)
  - [x] Migrate parts of ValidatingWebhook of LogPipeline which require CRD changes (https://github.com/kyma-project/telemetry-manager/pull/2539)
   - [x] Make sure that Go structs are properly named (e.g. LogPipeline specific types should be prefixed with LogPipeline, which is currently not the case)
  - [x] Introduce beta API for operator (https://github.com/kyma-project/telemetry-manager/pull/2561)
  - [x] Unify Enabled vs Disabled flags in pipeline specs
  - [x] Verify once more new TLS Disabled flag. Wasn't "Insecure" better?
- [ ] Rollout:
  - [X] Come up with a concrete action plan: https://github.com/kyma-project/telemetry-manager/issues/2729
  - [X] Pre-release
     - Conversion webhook is in place - done
     - Certificate handling for conversion webhook - done
     - Upgrade test in place to test all the signals work with v1beta1 - done
  - [ ] Release
     - Migrate the code: https://github.com/kyma-project/telemetry-manager/issues/2729
     - Check the CRs for all signal types are still accessible/editable
  - [ ] Post-release
     - Publish the information that v1alpha1 has been deprecated on the various channels and other communications and that users should update any helm chart
     - Update examples
     - Make sure all the CRs are written as beta in etcd then we can remove the alpha1 from CRD (use [storage migrator](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/storage-version-migration/#update-the-preferred-storage-schema-of-a-crd) or introduce interim condition)
     - Metrics in conversion webhook to check how often conversion webhook has been invoked to know v1alpha1 invocations
- [ ] Removal
  - Remove obsolete CRD version `v1alpha1`
    ```yaml
     versions:
     - name: v1beta1
       served: true
       storage: true
    ```
  - [Remove the old version](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#upgrade-existing-objects-to-a-new-stored-version) `v1alpha1` from the Status Subresource of the CRD `status.storedVersions`
   - This should be handled via KLM as per [OLM design doc](https://github.com/operator-framework/operator-lifecycle-manager/blob/5a5389cb8d831e79acade535d947d4ad4a5c40a7/doc/design/dependency-resolution.md#deprecateremove-a-version-of-crd) https://github.com/kyma-project/lifecycle-manager/issues/2905
  - Remove the conversion webhooks

**Comment by k15r** [comment]
**Important for the removal of the old crd version**
* create a script to update all existing CRs to the latest version (read it from API-Server, write it back in the latest version)
* mark the old version as `served: false`, `storage: false`
* remove the old version from the Status Subressource of the CRD `status.storedVersions`
* remove the old version from the spec of the CR

keep track of this issue: https://github.com/kyma-project/lifecycle-manager/issues/1545

**Comment by jeffreylimnardy** [comment]
All necessary PRs are merged, proceeding with v1beta1 rollout
