### ISSUE TITLE
[Telemetry Manager] Improved linter setup

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#86]
**Description**
In the past refactoring happened too late sometimes and code flaws sneaked into the source. In order to improve this, we like to add more linting.

**Criterias**
- Have an improved setup of our linting jobs by adding more rules, especially regarding code duplication, complexity and naming
- Job should be mandatory for PRs already
- There is an easy way to execute the check local (by make targets)
- There is a documented way to suppress findings

**Subtasks**

**Linter (golangci-lint)**

- [x] Sift and configure linters _(95 of 95)_
- [x] Group designated linters into presets
- [x] Document linters, linters' configuration and presets
- [x] Refactor the codebase to conform to the linting rules

**CI pipeline**

- [x] Provide IDE integrations for code linting
- [x] Readjust Make targets
- [x] Add a Make target for automatic fixing for the imports module imports.
- [x] <del>Define CI-pipeline guard (commit) stage</del>

**Code-style impacts**
- [x] <del>Team brainstorming on linting rules for test suite and subjective linters</del>
- [x] Document code-style impacts

**Comment by ameteiko** [comment]
Due to the numerous linters (around 90 at the moment), the full-fledged analysis for a codebase can take a noticeable amount of time, leading to disruptions in the development process.

Aiming for instant code style feedback during development, I suggest to group linter analysis into distinct stages:

- **Instant feedback** (a small subset of fast essential linters) to be configured as a file-watcher to react to each file change.

- **Autofix** (an action that auto-fixes the discovered errors and code-style problems) to be invoked on pre-commit (pre-push) git event (never to be performed on the CI side).

- **Full-fledged analysis** (with comprehensive linting coverage) to be invoked on pre-commit (pre-push) and as a guard stage in the CI pipeline.

![Image](https://user-images.githubusercontent.com/1386964/226841682-a8712d30-3c17-4b1f-92de-844ab3a116a6.png)

**Comment by ameteiko** [comment]
## Active linters

| Linter                                                                                                                | Description                                                                     | Suppress                           |
| ----------------------------------------------------------------------------------------------------------------------| ------------------------------------------------------------------------------- | ---------------------------------- |
| [`errcheck`](https://github.com/kisielk/errcheck) [⛭](https://golangci-lint.run/usage/linters/#errcheck)                                                          | checks for unhandled errors                                      | [inline //nolint](#inline-no-lint) |
| `exportloopref`                                                                                                                                                   | finds exporting pointers for loop variables                      | [inline //nolint](#inline-no-lint) |
| [`ginkgolinter`](https://github.com/nunnatsa/ginkgolinter) [⛭](https://golangci-lint.run/usage/linters/#ginkgolinter)                                             | enforces standards of using ginkgo and gomega                    | [inline //nolint](#inline-no-lint) |
| `gochecknoinits`                                                                                                                                                  | checks that no init functions are present                        | [inline //nolint](#inline-no-lint) |
| [`gofmt`](https://pkg.go.dev/cmd/gofmt) [⛭](https://golangci-lint.run/usage/linters/#gofmt)                                                                       | checks whether code was [gofmt](https://pkg.go.dev/cmd/gofmt) ed |                                    |
| [`gosec`](https://github.com/securego/gosec) [⛭](https://golangci-lint.run/usage/linters/#gosec)                                                                  | inspects source code for security problems                       | [inline //nolint](#inline-no-lint) |
| [`govet`](https://pkg.go.dev/cmd/vet) [⛭](https://golangci-lint.run/usage/linters/#govet)                                                                         | examines Go source code and reports suspicious constructs        | [inline //nolint](#inline-no-lint) |
| [`ineffassign`](https://github.com/gordonklaus/ineffassign)                                                                                                       | detects when assignments to existing variables are not used      | [inline //nolint](#inline-no-lint) |
| [`misspell`](https://github.com/client9/misspell) [⛭](https://golangci-lint.run/usage/linters/#misspell)                                                          | finds commonly misspelled English words in comments              | [inline //nolint](#inline-no-lint) |
| [`revive`](https://github.com/mgechev/revive) [⛭](https://golangci-lint.run/usage/linters/#revive)                                                                | comprehensive golint replacement                                 | [inline //nolint](#inline-no-lint) |
| [`staticcheck`](https://staticcheck.io/docs/checks/) [⛭](https://golangci-lint.run/usage/linters/#staticcheck)                                                    | performs static code analysis                                    | [inline //nolint](#inline-no-lint) |
| [`stylecheck`](https://github.com/dominikh/go-tools/tree/master/stylecheck) [⛭](https://golangci-lint.run/usage/linters/#stylecheck)                              | examines Go code-style conformance                               | [inline //nolint](#inline-no-lint) |
| `typecheck`                                                                                                                                                       | parses and type-checks Go code                                   | [inline //nolint](#inline-no-lint) |
| [`unparam`](https://github.com/mvdan/unparam) [⛭](https://golangci-lint.run/usage/linters/#unparam)                                                               | reports unused function parameters                               | [inline //nolint](#inline-no-lint) |
| [`unused`](https://github.com/dominikh/go-tools/tree/master/unused)                                                                                               | checks for unused constants, variables, functions and types      | [inline //nolint](#inline-no-lint) |
| [`asasalint`](https://github.com/alingse/asasalint) [⛭](https://golangci-lint.run/usage/linters/#asasalint)                                                       | check for pass []any as any in variadic func                     | [inline //nolint](#inline-no-lint) |
| [`asciicheck`](https://github.com/tdakkota/asciicheck)                                                                                                            | checks for non-ASCII identifiers                                 | [inline //nolint](#inline-no-lint) |
| [`bodyclose`](https://github.com/timakin/bodyclose)                                                                                                               | checks whether HTTP response body is closed successfully         | [inline //nolint](#inline-no-lint) |
| [`dogsled`](https://github.com/alexkohler/dogsled) [⛭](https://golangci-lint.run/usage/linters/#dogsled)                                                          | checks assignments with too many blank identifiers               | [inline //nolint](#inline-no-lint) |
| [`dupl`](https://github.com/mibk/dupl) [⛭](https://golangci-lint.run/usage/linters/#dupl)                                                                         | checks for code clone detection                                  |                                    |
| [`dupword`](https://github.com/Abirdcfly/dupword) [⛭](https://golangci-lint.run/usage/linters/#dupword)                                                           | checks for duplicate words in the source code                    | [inline //nolint](#inline-no-lint) |
| [`errchkjson`](https://github.com/breml/errchkjson) [⛭](https://golangci-lint.run/usage/linters/#errchkjson)                                                      | checks types passed to the json encoding functions               | [inline //nolint](#inline-no-lint) |
| [`gci`](https://github.com/daixiang0/gci) [⛭](https://golangci-lint.run/usage/linters/#gci)                                                                       | checks import order and ensures it is always deterministic       | [inline //nolint](#inline-no-lint) |
| [`gocheckcompilerdirectives`](https://github.com/leighmcculloch/gocheckcompilerdirectives)                                                                        | checks go compiler directive comments                            | [inline //nolint](#inline-no-lint) |
| [`goimports`](https://pkg.go.dev/golang.org/x/tools/cmd/goimports) [⛭](https://golangci-lint.run/usage/linters/#goimports)                                        | check import statements formatting                               | [inline //nolint](#inline-no-lint) |
| [`loggercheck`](https://github.com/timonwong/loggercheck) [⛭](https://golangci-lint.run/usage/linters/#loggercheck)                                               | checks key-value pairs for common logger libraries               | [inline //nolint](#inline-no-lint) |
| [`nolintlint`](https://github.com/golangci/golangci-lint/blob/master/pkg/golinters/nolintlint/README.md) [⛭](https://golangci-lint.run/usage/linters/#nolintlint) | reports ill-formed or insufficient nolint directives             | [inline //nolint](#inline-no-lint) |

## Irrelevant linters

Below is the list of linters irrelevant for Huskies team.

| Linter             | Reason                                                               |
| ------------------ | -------------------------------------------------------------------- |
| `bidichk`          | superseded by `stylecheck`                                           |
| `deadcode`         | superseded by `unused`                                               |
| `execinquery`      | `database/sql` package is not used                                   |
| `exhaustivestruct` | superseded by `exhaustruct`                                          |
| `forcetypeassert`  | superseded by `errcheck`                                             |
| `golint`           | superseded by `revive`, `stylecheck`                                 |
| `ifshort`          | deprecated                                                           |
| `interfacer`       | deprecated                                                           |
| `maligned`         | superseded by `govet`                                                |
| `nosnakecase`      | superseded by `revive`                                               |
| `promlinter`       | `github.com/prometheus/client_golang/prometheus` package is not used |
| `rowserrcheck`     | `database/sql` package is not used                                   |  
| `sqlclosecheck`    | `database/sql` package is not used                                   |  
| `scopelint`        | superseded by `exportloopref`                                        |
| `structcheck`      | superseded by `unused`                                               |
| `testableexamples` | Go Example functions are not used                                    |
| `varcheck`         | superseded by `unused`                                               |
| `wastedassign`     | superseded by `inefassign`                                           |
